USE [GD2C2020]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[CompraAuto]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[CompraAutoparte]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[FacturaAuto]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[FacturaAutoparte]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Auto]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[TipoAuto]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Autoparte]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[CategoriaAutoparte]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Modelo]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Fabricante]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Factura]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Compra]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Cliente]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Sucursal]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Caja]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Motor]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[Transmision]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_Tiempo]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_CategoriaAutoParte]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_Fabricante]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_Caja]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_Transmision]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_Motor]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_Modelo]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_Sucursal]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_Cliente]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_TipoAuto]
GO

DROP TABLE IF EXISTS [LOS_CUATRO_FANTASTICOS].[BI_Compra_Venta_Auto_Autoparte]
GO

DROP SCHEMA IF EXISTS [LOS_CUATRO_FANTASTICOS]
