USE [GD2C2020]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[CompraAuto]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[CompraAutoparte]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[FacturaAuto]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[FacturaAutoparte]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Auto]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[TipoAuto]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Autoparte]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[CategoriaAutoparte]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Modelo]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Fabricante]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Factura]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Compra]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Cliente]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Sucursal]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Caja]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Motor]
GO

DROP TABLE [LOS_CUATRO_FANTASTICOS].[Transmision]
GO

DROP SCHEMA [LOS_CUATRO_FANTASTICOS]


