
--CREO LA TABLA AUTO
CREATE TABLE Auto(
id INT PRIMARY KEY,
Chasis NVARCHAR(50) NULL,
Motor  NVARCHAR(50) NULL,
Patente NVARCHAR(50) NULL,
Fecha_Alta DATETIME2(3) NULL,
Cantidad_Kms DECIMAL(18,0) NULL,
TipoAutoCodigo DECIMAL(18,0) NOT NULL,
ModeloCodigo DECIMAL(18,0) NOT NULL,
)
GO


--CREO LA TABLA AUTOPARTE
CREATE TABLE Autoparte(
Codigo DECIMAL(18,0)  PRIMARY KEY,
Descripcion NVARCHAR(255)  NULL,
ModeloId DECIMAL(18,0) NOT NULL,
Categoria DECIMAL(18,0) NOT NULL,
TipoAutoparteCodigo DECIMAL(18,0) NOT NULL,
)
GO


--CREO LA TABLA TIPOAUTO
CREATE TABLE TipoAuto(
Codigo DECIMAL(18,0)  PRIMARY KEY,
Descripcion NVARCHAR(255)  NULL,
)
GO


--CREO LA TABLA TIPOAUTOPARTE
CREATE TABLE TipoAutoparte(
Codigo DECIMAL(18,0)  PRIMARY KEY,
Descripcion  NVARCHAR(255)  NULL,
)
GO


--CREO LA TABLA CATEGORIAAUTOPARTE
CREATE TABLE CategoriaAutoparte(
Codigo DECIMAL(18,0)  PRIMARY KEY,
Descripcion  NVARCHAR(255)  NULL,
)
GO


--CREO LA TABLA FABRICANTE
CREATE TABLE Fabricante(
Id INT PRIMARY KEY,
Nombre  NVARCHAR(255)  NULL,
)
GO


--CREO LA TABLA MODELO
CREATE TABLE Modelo(
Codigo DECIMAL(18,0)  PRIMARY KEY,
Nombre  NVARCHAR(50)  NULL,
Potencia  NVARCHAR(50)  NULL,
FabricanteId INT NOT NULL,
)
GO


--CREO LA TABLA FACTURACIONAUTO
CREATE TABLE FacturaAuto(
FacturaNumero DECIMAL(18,0),
AutoId  INT,
Precio  DECIMAL(18,2) NOT NULL,
PRIMARY KEY(FacturaNumero, AutoId)
)
GO


--CREO LA TABLA FACTURACIONAUTOPARTE
CREATE TABLE FacturaAutoparte(
FacturaNumero DECIMAL(18,0),
AutoparteId  INT,
Cantidad DECIMAL(18,2) NOT NULL,
Precio  DECIMAL(18,2) NOT NULL,
PRIMARY KEY(FacturaNumero, AutoparteId)
)
GO



--CREO CLAVE FORANIA DE LA TABLA AUTO CON  TIPOAUTO
ALTER TABLE Auto  
ADD CONSTRAINT fk_auto_tipoAuto FOREIGN KEY
(TipoAutoCodigo)
REFERENCES TipoAuto (Codigo)
GO



--CREO CLAVE FORANIA DE LA TABLA AUTO CON MODELO
ALTER TABLE Auto  
ADD CONSTRAINT fk_auto_modelo FOREIGN KEY
(ModeloCodigo)
REFERENCES Modelo (Codigo)
GO


--CREO CLAVE FORANIAS DE LA TABLA MODELO CON FABRICANTE

ALTER TABLE Modelo  
ADD CONSTRAINT fk_modelo_fabricante FOREIGN KEY
(FabricanteId)
REFERENCES Fabricante (Id)
GO



--CREO CLAVE FORANIAS DE LA TABLA AUTOPARTE CON TIPOAUTOPARTE
ALTER TABLE Autoparte  
ADD CONSTRAINT fk_autoParte_tipoAutoparte FOREIGN KEY
(TipoAutoparteCodigo)
REFERENCES TipoAutoparte (Codigo)
GO

--CREO CLAVE FORANIAS DE LA TABLA AUTOPARTE CON  MODELO
ALTER TABLE Autoparte  
ADD CONSTRAINT fk_autoParte_modelo FOREIGN KEY
(ModeloId)
REFERENCES Modelo (Codigo)
GO


--CREO CLAVE FORANIAS DE LA TABLA AUTOPARTE CON CATEGORIAAUTOPARTE

ALTER TABLE Autoparte  
ADD CONSTRAINT fk_autoParte_categoriaAutoparte FOREIGN KEY
(Categoria)
REFERENCES CategoriaAutoparte (Codigo)
GO